In [1]:
import numpy as np

In [2]:
b = np.array([[1,3,5,7],[2,4,6,8],[1,4,9,4]])          #array of 3x4
b

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [1, 4, 9, 4]])

In [4]:
#syntax:- mat[row index, column index]
b[1,2]

6

In [5]:
a = np.random.randint(1,50,(8,8))
print (a)

[[21 28  5 31 18 29 36  1]
 [ 1  1 14 16 12 40 48 36]
 [44 38 45 13 22 49 31 49]
 [ 3 10 18 37  7 18  1 43]
 [29 39 33 38 25 40 44  8]
 [46  4 28 29 31  1 25  4]
 [47  2 37  6  5 48 45  8]
 [19  7 17 24 31 14  1  4]]


In [6]:
a[1,2]        #element at row 1 and coumn 2

14

In [7]:
a[3]         #display row 3

array([ 3, 10, 18, 37,  7, 18,  1, 43])

In [8]:
a[-2]     #display the last 2nd row

array([47,  2, 37,  6,  5, 48, 45,  8])

In [9]:
#mat[row slicing, column slicing]
#row slicing: [start:stop+1: step]
#column slicing: [start:stop+1:step]

In [12]:
a[0:5:1,2:7:1]        #both row and column slicing

array([[47,  8, 44,  1,  6],
       [ 6,  7, 23, 23, 37],
       [28,  2, 33,  7, 46],
       [45, 37, 48,  6, 12],
       [41, 27,  5, 45, 32]])

In [13]:
a[::,0:8:2]    #column slicing only, but display all rows

array([[ 5, 47, 44,  6],
       [39,  6, 23, 37],
       [40, 28, 33, 46],
       [40, 45, 48, 12],
       [38, 41,  5, 32],
       [ 7, 41, 17,  5],
       [47, 18,  8, 33],
       [45, 31,  7, 49]])

In [14]:
#concatenation

In [15]:
a = np.array([[1,2,3],[8,9,5],[7,4,10]])
b = np.array([[2,3,4],[8,9,3],[3,6,9]])

print(a)
print(b)

[[ 1  2  3]
 [ 8  9  5]
 [ 7  4 10]]
[[2 3 4]
 [8 9 3]
 [3 6 9]]


In [16]:
np.concatenate((a,b),axis=0)       #by default it is row wise concatenation, axis=0

array([[ 1,  2,  3],
       [ 8,  9,  5],
       [ 7,  4, 10],
       [ 2,  3,  4],
       [ 8,  9,  3],
       [ 3,  6,  9]])

In [17]:
np.concatenate((a,b),axis=1)       #for column, axis=1

array([[ 1,  2,  3,  2,  3,  4],
       [ 8,  9,  5,  8,  9,  3],
       [ 7,  4, 10,  3,  6,  9]])

In [18]:
#vertical stack-> rowwise
#horizontal stack-> columnwise

In [20]:
np.vstack((a,b))      #vertically/rowise joining

array([[ 1,  2,  3],
       [ 8,  9,  5],
       [ 7,  4, 10],
       [ 2,  3,  4],
       [ 8,  9,  3],
       [ 3,  6,  9]])

In [21]:
np.hstack((a,b))      #horizontally/columnise joining

array([[ 1,  2,  3,  2,  3,  4],
       [ 8,  9,  5,  8,  9,  3],
       [ 7,  4, 10,  3,  6,  9]])