In [5]:
def cel2far(t):
    c=((t*9)/5)+32
    return c

n=float(input("Enter temperature in Celsius: "))
print("The temp is:",cel2far(n),"F")

print("\nThe temperature table is as under")
for i in range(10,41,10):
    print(i,"C"," = ",cel2far(i),"F")

Enter temperature in Celsius: 10
The temp is: 50.0 F

The temperature table is as under
10 C  =  50.0 F
20 C  =  68.0 F
30 C  =  86.0 F
40 C  =  104.0 F


In [11]:
def vowels(en):
    c=0
    vowel="aeiouAEIOU"
    for i in en:
        if i in vowel:
            c+=1
    return c

def  spacing(en):
    c=0
    for i in en:
        if i.isspace():
            c+=1
    return c

def consonants(en):
    c=0
    for i in en:
        if i.isalpha():
            c+=1
    c-=vowels(en)
    return c

n=input("Enter any sentence: ")

print("The number of vowels is:",vowels(n))
print("The number of consonants is:",consonants(n))
print("The number of spaces is:",spacing(n))

Enter any sentence: Hello I am Soham
The number of vowels is: 6
The number of consonants is: 7
The number of spaces is: 3


In [2]:
def rec(s):
    vowel = 'aeiouAEIOU'
    if s=='':
        return 0
    elif s[0] in vowel:
        return 1 + rec(s[1:])
    else: 
        return 0 + rec(s[1:])


In [3]:
rec("Hello I am Soham")

6

# Numpy

In [3]:
import numpy as np

In [4]:
np.__version__

'1.21.5'

In [13]:
#1-D array
a = np.array([1,2,3,4,5])     #creattion of a single dimensional array
a

array([1, 2, 3, 4, 5])

In [6]:
type(a)       #type of is a multi-dimensional/ndarray 

numpy.ndarray

In [7]:
id(a)       #location of array 'a'

2322805698064

In [8]:
arr = a

In [10]:
id(arr)    #'arr' is just an other name for 'a'

2322805698064

In [11]:
a1 = np.copy(a)    #'a1' takes value of 'a' such that 

In [16]:
id(a1)         #location of 'a1' is different than that of 'a'

2322801711600

In [17]:
t = (1,2,3,4,5)    #tuple type of element
t

(1, 2, 3, 4, 5)

In [18]:
type(t)

tuple

In [19]:
b = np.array(t)      #tuple converted to array

In [20]:
b

array([1, 2, 3, 4, 5])

In [21]:
type(b)

numpy.ndarray

In [22]:
#creating array from dictionary
d={'a':1,'b':2,'c':3}
type(d)

dict

In [23]:
c=np.array(d)       #dictionary to array conversion
c

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [24]:
type(c)

numpy.ndarray

In [25]:
#2-D array
a = np.array([[1,2,3,4],[2,5,6,8]])     #two dimensional array
a

array([[1, 2, 3, 4],
       [2, 5, 6, 8]])

In [26]:
type(a)

numpy.ndarray

In [28]:
a = np.array([[1,2,3,4,5],[2,5,6,8]])   #cannot take unequal number of column elements for rows
a

C:\Users\CTTC1\AppData\Local\Temp\ipykernel_9912\441914430.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[1,2,3,4,5],[2,5,6,8]])   #cannot take unequal number of column elements for rows


array([list([1, 2, 3, 4, 5]), list([2, 5, 6, 8])], dtype=object)

In [42]:
a = np.array([list([1, 2, 3, 4, 5]), list([2, 5, 6, 8])], dtype=object)   #the elements are declared as lists
a

array([list([1, 2, 3, 4, 5]), list([2, 5, 6, 8])], dtype=object)

In [43]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])          #multidimensional array declaration
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
#arrange
np.arange(1,11)         #generates evenly spaced numbers from 0 to 10; arange(start,stop+1,step)-> step is in integer

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [53]:
#1-D 0 array
np.zeros(4)

array([0., 0., 0., 0.])

In [56]:
#multi dimensional 0 array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
#ones array
np.ones(5)

array([1., 1., 1., 1., 1.])

In [58]:
#multi dimensional ones array
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
#full array
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [62]:
np.full(3,(4,5))

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [76]:
#linspace-> equally distributed numbers between some range
# linspace(start, stop, no. of elements)
print(np.linspace(1,100,10))

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [77]:
#array attributes
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
np.size(a)                 #total number of elements

12

In [80]:
type(a)                #type of variable

numpy.ndarray

In [82]:
a.shape          #shape of the array

(3, 4)

In [83]:
a.dtype             #data type of array

dtype('int32')

In [101]:
a.astype('float32')           #change the type to 'float32'

In [102]:
a.dtype

dtype('float32')

In [105]:
b = a.astype('float')
b.dtype

dtype('float64')

In [106]:
a.ndim          #number of dimension of the array

2

In [107]:
b.ndim

2

In [108]:
#indentity matrix : eye
np.eye(5)                 #creates an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [109]:
# convert array to list
a.tolist()                 

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [110]:
np.info(np.eye)             #information about a command

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible wi

In [111]:
a = np.array(a)

In [112]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [120]:
#random number generation
np.random.rand()     # random number between 0 and 1

0.2225883712103751

In [122]:
np.random.rand(3,4)    #3x4 matrix with numbers filled by anything between 0 and 1

array([[0.50034102, 0.93830578, 0.28386209, 0.54316164],
       [0.60742749, 0.12154824, 0.62176821, 0.02874539],
       [0.27268774, 0.51058299, 0.63637694, 0.19921221]])

In [123]:
np.random.rand(10)     # 10 random number between 0 and 1 

array([0.28851365, 0.8970073 , 0.09859145, 0.14654265, 0.72378725,
       0.16184553, 0.58469301, 0.29612877, 0.85738032, 0.28260601])

In [124]:
np.random.rand(3,4)*100    #3x4 matrix with float numbers filled by anything between 1 and 100

array([[41.59859174, 24.84155136, 98.21309992, 88.48979408],
       [17.58506352, 19.8939853 , 43.69602281,  9.71610121],
       [75.19906721, 94.32327758, 61.63871313, 49.53638699]])

In [126]:
np.random.randint(1,10)    #int number anything between 1 and 10

6

In [41]:
np.random.randint(1,10,(2,3)) 
#2x3 matrix filled with int numbers anything between 1 and 10

array([[7, 1, 5],
       [7, 7, 1]])

# Mathematical operations


In [128]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

In [130]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [131]:
a + b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [132]:
np.add(a,b)   #addition between 2 arrays

array([[ 8, 10, 12],
       [14, 16, 18]])

In [134]:
np.subtract(a,b)      #perform substraction between 2 arrays

array([[-6, -6, -6],
       [-6, -6, -6]])

In [135]:
np.multiply(a,b)      #multiplication between 2 arrays

array([[ 7, 16, 27],
       [40, 55, 72]])

In [136]:
np.divide(a,b)          #divide one array by another

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [137]:
np.mod(a,b)             #remainder when 1 array is divided by another array

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [140]:
np.floor_divide(b,a)         #divides and returns remainder when 1 array is divided by another

array([[7, 4, 3],
       [2, 2, 2]], dtype=int32)

In [145]:
c = np.power(b,2)            #raises the elements of an array to a certain power
c

array([[ 49,  64,  81],
       [100, 121, 144]], dtype=int32)

In [144]:
np.sqrt(c)              #square root of an array

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [146]:
np.log(c)              #finds the 'log' of elements of an array

array([[3.8918203 , 4.15888308, 4.39444915],
       [4.60517019, 4.79579055, 4.9698133 ]])

In [147]:
np.sin(a)           #finds 'sin' of elements of an array

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [149]:
np.tan(b)          #finds 'cos' of elements of an array

array([[   0.87144798,   -6.79971146,   -0.45231566],
       [   0.64836083, -225.95084645,   -0.63585993]])

# Statistical functions


In [150]:
a.min()               #finds the minimum value stored in an array

1

In [151]:
a.max()           #finds the maximum value stored in an array

6

In [155]:
a.mean()          #finds the mean of the elements of an array

3.5

In [156]:
np.median(a)        #finds the median of elements of an array

3.5

In [157]:
a.std()             #finds the standard deviation of elements of an array

1.707825127659933

In [158]:
a.var()            #finds the variance of elements of an array

2.9166666666666665

In [159]:
a.cumsum()         #finds the cumulative sum of elements of an array

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

# Repeat

In [1]:
import numpy as np
b = np.array([1,2,3])
print(b)

[1 2 3]


In [163]:
print(np.repeat(b,4))           #repeat each element of an array for 4 times

[1 1 1 1 2 2 2 2 3 3 3 3]


In [165]:
c = np.array([2,4,3])
print(c)
np.tile(c,3)          #repeats all elements of an array for 3 times

[2 4 3]


array([2, 4, 3, 2, 4, 3, 2, 4, 3])

In [173]:
#max and min index position
c = np.array([3,4,2,5,6,7,8])
np.argmax(c)      #index position of maximum value

6

In [174]:
np.argmin(c)      #index position of minimum value

2

In [2]:
a = np.array([2,3,2,2,4,4,4,5,4])

In [176]:
np.where(a==4)            #returns the different number of indexes of the elemnt

(array([4, 5, 6, 8], dtype=int64),)

In [179]:
np.argsort(a)    #output is in terms of index

array([0, 2, 3, 1, 4, 5, 6, 8, 7], dtype=int64)

In [182]:
np.argpartition(a,5)    
#output is like the left of the elements has the lesser values and the right side has more values

array([6, 0, 2, 3, 1, 4, 5, 7, 8], dtype=int64)

In [187]:
np.transpose(a)     #a row matrix or a column matrix acnnot be transpose

array([2, 3, 2, 2, 4, 4, 4, 5, 4])

In [188]:
a = np.array([[1,2,3],[4,5,6]])
np.transpose(a)                  #print the transpose of matrix 'a'

array([[1, 4],
       [2, 5],
       [3, 6]])

In [189]:
#vector maths

In [197]:
a = np.array([[1,2],[4,5]]) 
b = np.array([[1,3],[5,6]])

print(a)
print(b)

[[1 2]
 [4 5]]
[[1 3]
 [5 6]]


In [198]:
np.dot(a,b)

array([[11, 15],
       [29, 42]])

In [199]:
np.cross(a,b)

array([ 1, -1])

In [202]:
print(a)
print(np.transpose(a))            #returns the transpose of 'a', row changes to column and column changes to row

[[1 2]
 [4 5]]
[[1 4]
 [2 5]]


In [203]:
a = np.array([1,1,1,1,2,2,2,2,3,3,3,3,3,3,])
a

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3])

In [204]:
np.unique(a)           #returns only the unique elements in the matrix 'a'

array([1, 2, 3])

In [206]:
#indexing and slicing
a = np.array([2,3,4,5,6,4,7,8,9,10])

In [207]:
a[5]           #prints only that element, which is at the index [5]

4

In [209]:
a[1:9:2]    #[start:stop+1:step]-> slicing example

array([3, 5, 4, 8])

In [210]:
b = np.array([[1,3,5,7],[2,4,6,8],[1,4,9,4]])
b

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [1, 4, 9, 4]])

In [211]:
#syntax:- mat[row index, column index]
b[1,2]               #returns the elements at the specified row and column number

6

In [52]:
import numpy as np
a = np.random.randint(1,100,(3,3))     #generates a random number between 1 and 100, and makes a matrix of 3x3 with those numbers
a

array([[22, 71, 30],
       [87, 18, 40],
       [63, 21, 47]])

In [53]:
a = np.random.randint(1,100,(8,8))
a

array([[92, 89, 13, 11, 39, 26, 40, 68],
       [45, 66, 50, 25,  2, 17, 64, 28],
       [91, 41, 90, 99,  1, 48, 24, 96],
       [93, 14, 70, 63, 31, 46,  7, 22],
       [16,  9, 93, 45,  8, 28, 30, 52],
       [ 6, 39, 63, 38, 86, 52, 24, 92],
       [57, 55, 87, 72, 37, 93, 60, 28],
       [17, 91, 66, 70, 71, 57, 66, 20]])

In [55]:
a[6]

array([57, 55, 87, 72, 37, 93, 60, 28])

In [57]:
a[1:6:1]      #row slicing

array([[45, 66, 50, 25,  2, 17, 64, 28],
       [91, 41, 90, 99,  1, 48, 24, 96],
       [93, 14, 70, 63, 31, 46,  7, 22],
       [16,  9, 93, 45,  8, 28, 30, 52],
       [ 6, 39, 63, 38, 86, 52, 24, 92]])

In [59]:
a[::,1:6:1]      #column slicing

array([[89, 13, 11, 39, 26],
       [66, 50, 25,  2, 17],
       [41, 90, 99,  1, 48],
       [14, 70, 63, 31, 46],
       [ 9, 93, 45,  8, 28],
       [39, 63, 38, 86, 52],
       [55, 87, 72, 37, 93],
       [91, 66, 70, 71, 57]])

In [58]:
a[1:6:1,1:5:1]     #both row and column slicing

array([[66, 50, 25,  2],
       [41, 90, 99,  1],
       [14, 70, 63, 31],
       [ 9, 93, 45,  8],
       [39, 63, 38, 86]])